---
title: "Zumwalt Tablet data processing"
author: "Alexander Traynor"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
  word_document: default

---

# Import Height Weight Data

```{r setup}
library(readxl)
library(tidyverse)
library(dplyr)
```

# write code to tidy data
# make into function
# loop function over files in directory

```{r}
folder <- "C:\\Users\\Alexander\\OneDrive - University of Idaho\\UI\\Thesis\\Grouse and Grazing\\Zumult\\Data Analysis\\TEST_001.xlsx"

metadata <- readxl::read_xlsx(path = folder,
                          sheet = 1, 
                          range = "A1:O3", 
                          col_names = FALSE)
metadata <- metadata[,c(1,4,9,10)]
metadata1 <- metadata[,c(1,2)]
metadata1 <- metadata1 %>% 
  spread(key = "...1", value = "...4")

metadata2 <- metadata[,c(3,4)]
metadata2 <- metadata2 %>% 
  spread(key = "...9", value = "...10")

metadata <- cbind(metadata1,metadata2)

hwdata <- readxl::read_xlsx(path = "C:\\Users\\Alexander\\OneDrive - University of Idaho\\UI\\Thesis\\Grouse and Grazing\\Zumult\\Data Analysis\\TEST_001.xlsx",
                          sheet = 1, 
                          range = "A6:O34", 
                          col_names = FALSE)

hwdata <- hwdata[c(4:29),]
colnames(hwdata) <- as.character(unlist(hwdata[1,]))
hwdata <- hwdata[-1,]
t1 <- hwdata[,1:5]
t1$Transect <- 1
t2 <- hwdata[,6:10]
t2$Transect <- 2
t3 <- hwdata[,11:15]
t3$Transect <- 3

hwdata <- rbind(t1,t2,t3)

plotdata <- cbind(metadata,hwdata)
```


